---
- name: Установка и настройка quagga
  hosts:
    - all
  gather_facts: no
  remote_user: vagrant
  become: true

  - tasks:
      - name: Устанавливаем quagga
          yum:
            name: quagga
            state: persent

- name: Копируем конфиги
    copy:
      src: /usr/share/doc/quagga-0.99.22.4/zebra.conf.sample
      dest: /etc/quagga/zebra.conf

- name: Запускаем quagga
    systemd:
      name: quagga
      enabled: yes
      state: started